version: "3.8"

services:
  nextjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: 
    volumes:
      - /next/node_modules
      - ./next:/next
    ports:
      - 3000:3000
    command: npm run dev
    environment:
      - WATCHPACK_POLLING=true
